yaroslavche_sylius_plugin_marketplace_plugin_index:
  path: /admin/plugins/
  controller: Yaroslavche\SyliusPluginMarketplacePlugin\Controller\MarketplaceController::index

yaroslavche_sylius_plugin_marketplace_plugin_list:
  path: /admin/plugins/list
  controller: Yaroslavche\SyliusPluginMarketplacePlugin\Controller\MarketplaceController::list

