services:
  app.listener.admin.menu_builder:
    class: Yaroslavche\SyliusPluginMarketplacePlugin\Listener\AdminMenuListener
    tags:
      - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

  yaroslavche_sylius_plugin_marketplace_plugin_plugin_marketplace: # xD
    class: Yaroslavche\SyliusPluginMarketplacePlugin\PluginMarketplace\PluginMarketplace
    autowire: true
    autoconfigure: true
    arguments:
      $rootDir: '%kernel.project_dir%'

  Yaroslavche\SyliusPluginMarketplacePlugin\PluginMarketplace\PluginMarketplace: '@yaroslavche_sylius_plugin_marketplace_plugin_plugin_marketplace'

  Yaroslavche\SyliusPluginMarketplacePlugin\Controller\PluginMarketplaceController:
    arguments:
      $pluginMarketplace: '@yaroslavche_sylius_plugin_marketplace_plugin_plugin_marketplace'
    tags: ['controller.service_arguments']
